name: Build V1

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: cd basic_lab02_02-master && npm ci
      - name: Lint
        run: cd basic_lab02_02-master && npm run lint
      - name: Test code
        run: cd basic_lab02_02-master && npm run test
      - name: Deploy code
        run: echo "Deploying..."